name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para despliegues

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY || '{}' }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/workshop-services .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/workshop-services

    - name: Deploy to Cloud Run
      run: gcloud run deploy workshop-services --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/workshop-services --platform managed --region ${{ secrets.GCP_REGION }}
